version: '3'

services:
  firebase:
    build: ./docker/firebase
    volumes:
      - ./firebase/functions:/firebase/functions
      - ./firebase/rules:/firebase/rules
      - ./firebase/.firebaserc:/firebase/.firebaserc
      - ./firebase/firebase.json:/firebase/firebase.json
      - ./firebase/firestore.indexes.json:/firebase/firestore.indexes.json
      - ./app/dist:/firebase/public
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    networks:
      default:

volumes:
  default:

networks:
  default:

